### PR TITLE
Changed jQuery calls from "$" to "jQuery" to improve WP compatibility

### PR DESCRIPTION
**Pull request by nkegles**

### CODE REVIEW

**Comment by webbiesdk** [comment]
The only place where i can see that this could make a difference, is the one on line 33. 

The rest are just renaming a local variable, so why would that help?

**Comment by nkegles** [comment]
only to maintain the nomenclature, wait...

**Comment by nkegles** [comment]
only to maintain the nomenclature

**Comment by nkegles** [comment]
but replacing in all file add some bytes to plugin, is good replace only in line 33 :)

**Comment by webbiesdk** [comment]
I don't know if i completely get what it is you are saying. 

But if you could change the pull-request, so that it only makes the change on line 33, that would be great. (You can also create a new pull-request, if that is easier).

**Pull request closed without merging**
